### ISSUE TITLE
Unable to load resources.

### ISSUE THREAD

**Issue by RomanZavodskikh** [Gumil9/Ciscer#1]
При попытке использовании Ciscer на данном коммите возникает ошибка Unable to load resources.
Я честно пытался понять, из-за чего, своими силами, но что-то не вышло.
![screenshot_2017-03-24_00-42-54](https://cloud.githubusercontent.com/assets/8851784/24271662/010a8244-102b-11e7-9a8f-96923e84d1c8.png)

**Comment by Gumil9** [comment]
Да, по сообщению в консоли вообще не понятно, где ошибка, постараюсь исправить.

**Comment by olegrok** [comment]
Проверяй точки с запятой в коде.

**Comment by Gumil9** [comment]
Окно с ошибкой "Unable to load resources" возникает тогда, когда код ответов либо не удалось загрузить, либо не удалось выполнить (из-за ошибок в файле с ответами).

При добавлении ответов на тест рекомендую пользоваться редактором с подсветкой синтаксиса: все опечатки в коде видны сразу. Например, можно использовать JetBrains Idea (только Ultimate Edition, можно получить по .edu-почте), Visual Studio и др.

Если ничего такого не установлено, можно воспользоваться [JSHint](http://jshint.com/): вставляете туда код и справа смотрите все ошибки и предупреждения. Не обращайте внимания на ошибку `Two undefined variables: tests, prompts`, они определены в вызывающем код с ответами контексте. Других ошибок быть не должно.
